# Generated by Django 5.0.14 on 2026-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='age',
        ),
        migrations.AddField(
            model_name='registration',
            name='age_group',
            field=models.CharField(choices=[('13-17', '13–17'), ('18-25', '18–25'), ('26-35', '26–35'), ('36-45', '36–45'), ('46-55', '46–55'), ('56+', '56+')], default='18-25', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_locci_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='locci_branch',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
