# Generated by Django 5.0.14 on 2026-08-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
